name: build

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  code-style:
    uses: ./.github/workflows/code-style.yml

  android-build:
    uses: ./.github/workflows/android-build.yml

  unit-tests:
    uses: ./.github/workflows/test.yml

  publish-github-release:
    name: Publish GitHub Release
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [code-style, android-build, unit-tests]
    uses: ./.github/workflows/publish-github-release.yml

  publish-gitee-release:
    name: Publish Gitee Release
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [code-style, android-build, unit-tests]
    uses: ./.github/workflows/publish-gitee-release.yml
